TRI_LAYER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
OS_DETECTION_ENABLE = yes

# debugging
CONSOLE_ENABLE = no

SRC += lightning.c
